---
## Configure the client in the backuppc server

- name: Configure the client backups in BackupPC server
  block:
  
  - name: TEMPLATE | Put host specific config on BackupPC server
    template:
      src: etc/backuppc/_host_config.pl.j2
      dest: '{{ backuppc_server_config_dir }}/{{ inventory_hostname }}.pl'
      owner: '{{ backuppc_server_user }}'
      group: '{{ backuppc_server_group }}'
      mode: 0644
    when: backuppc_backup_state == 'present'
    notify: backuppc_client - restart backuppc

  - name: FILE | Delete config if needed
    file: 
      path: '{{ backuppc_server_config_dir }}/{{ inventory_hostname }}.pl'
      state: absent
    when: backuppc_backup_state == 'absent'
    notify: backuppc_client - restart backuppc

  - name: LINEINFILE | Add host to BackupPC server
    lineinfile:
      dest: '{{ backuppc_server_config_dir }}/hosts'
      line: "{{ inventory_hostname }}\t0\t{{ backuppc_server_web_main_user }}\t{{ backuppc_server_web_other_users }}"
      regexp: '^{{ inventory_hostname }}'
      state: '{{ backuppc_backup_state }}'
  
  delegate_to: '{{ backuppc_server_name }}'

...
