---
# Configure the backuppc user in the client host to backup

- name: APT |Instalar Rsync
  apt:
    name: rsync
    state: present

- name: GROUP | Create unix group 'backuppc_client_group' in the client
  group:
    name: "{{ backuppc_client_group }}"
    state: present

- name: USER | Create unix user 'backuppc_client_user' in the client
  user:
    name: "{{ backuppc_client_user }}"
    home: '{{ backuppc_client_home }}'
    shell: /bin/bash
    groups: "{{ backuppc_client_group }}"

- name: FILE |  Create the user's ssh data in the client
  file:
    path: '{{ backuppc_client_home }}/.ssh'
    state: directory
    owner: "{{ backuppc_client_user }}"
    group: "{{ backuppc_client_group }}"
    mode: 0700

- name: LINEINFILE | Define cmnd_alias to allow 'backuppc' privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^Cmnd_Alias BACKUPS'
    line: '{{ backuppc_sudoer }}'
    validate: 'visudo -cf %s'

- name: LINEINFILE | Allow 'backuppc' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ backuppc_client_group }}'
    line: '%{{ backuppc_client_group }} ALL=(ALL) NOPASSWD: BACKUPS'
    validate: 'visudo -cf %s'

...
