---
## backuppc_client role's tasks

- name: INCLUDE | install rsync and backuppc user
  import_tasks: install.yml
  when: backuppc_client

- name: INCLUDE | config user mysql
  import_tasks: mysql_config.yml
  when: backuppc_client and backuppc_db_server_type == 'mysql'

- name: INCLUDE | config PostgreSQL
  import_tasks: pgsql_config.yml
  when: backuppc_client and backuppc_db_server_type == 'pgsql'

- name: INCLUDE | add file bash
  import_tasks: copy_scripts.yml
  when: backuppc_client and backuppc_scripts

- name: INCLUDE | Backuppc server configuration
  import_tasks: config.yml

- name: INCLUDE | SSH to server related configuration
  import_tasks: ssh.yml

...
