---
## Configure backuppc user ssh server key in the client

- name: install server ssh key in client
  block: 
  - name: COMMAND | Extract SSH backuppc server pub key
    command: "cat {{ backuppc_server_home }}/.ssh/id_rsa.pub"
    register: cat
    changed_when: false
    delegate_to: "{{ backuppc_server_name }}"

  - name: Add SSH server pub key to client
    sudo: yes
    authorized_key:
      user: backuppc
      state: present
      key: "{{ cat.stdout }}"
    delegate_to: "{{ inventory_hostname }}"
  when: backuppc_client

- name: ssh public key of client
  shell: "ssh-keyscan {{ inventory_hostname }}"
  register: ssh_known_host_results
  ignore_errors: yes
  delegate_to: "{{ backuppc_server_name }}"

- name: add client key to known_hosts in server
  known_hosts:
    path: '{{ backuppc_server_home }}/.ssh/known_hosts'
    name: "{{ inventory_hostname }}"
    key: "{{ ssh_known_host_results.stdout }}"
    state: present
  delegate_to: "{{ backuppc_server_name }}"