---

- name: restart backuppc
  action: service name=backuppc state=restarted enabled=yes
  delegate_to: "{{backuppc_server_name}}"

- name: restart apache2
  action: service name=apache2 state=restarted enabled=yes
  delegate_to: "{{backuppc_server_name}}"


